function unicode_to_surekh()
{var array_one=new Array("à¤•à¤¼à¥","à¤–à¤¼à¥","à¤—à¤¼à¥","à¤œà¤¼à¥","à¤«à¤¼à¥","à¤•à¤¼","à¤–à¤¼","à¤—à¤¼","à¤œà¤¼","à¤«à¤¼","à¤¡à¤¼","à¤¢à¤¼","à¥","à¤½","à¤ƒ","à¥¤","à¤¶à¥à¤°à¥","à¤¶à¥à¤°","à¤‘","à¥‰","à¤“à¤‚","à¤”à¤‚","à¤“","à¤”","à¤†","à¤…","à¤ˆ","à¤‡","à¤Š","à¤‰","à¤‹","à¥ ","à¤","à¤","à¤•à¥à¤°","à¤•à¥à¤¤","à¤•à¥à¤·à¥","à¤•à¥à¤·","à¥˜à¥","à¥˜","à¤•à¥","à¤•","à¥™à¥","à¥™","à¤–à¥à¤°à¥","à¤–à¥","à¤–","à¥šà¥","à¥š","à¤—à¥à¤°à¥","à¤—à¥à¤°","à¤—à¥","à¤—","à¤˜à¥à¤°à¥","à¤˜à¥","à¤˜","à¤™","à¤šà¥à¤°à¥","à¤šà¥","à¤š","à¤›","à¥›à¥","à¥›","à¤œà¥à¤°à¥","à¤œà¥à¤žà¥","à¤œà¥à¤ž","à¤œà¥","à¤œ","à¤à¥à¤°à¥","à¤à¥","à¤","à¤žà¥","à¤ž","à¤Ÿà¥à¤Ÿ","à¤Ÿà¥à¤ ","à¤Ÿ","à¤ à¥à¤ ","à¤ ","à¥œ","à¤¡à¥à¤¡","à¤¡à¥à¤¢","à¤¡","à¥","à¤¢","à¤£à¥","à¤£","à¤¤à¥à¤°à¥","à¤¤à¥à¤°","à¤¤à¥à¤¤à¥","à¤¤à¥à¤¤","à¤¤à¥","à¤¤","à¤¥à¥à¤°à¥","à¤¥à¥","à¤¥","à¤¦à¥ƒ","à¤¦à¥à¤°","à¤¦à¥à¤¦","à¤¦à¥à¤§","à¤¦à¥à¤®","à¤¦à¥à¤¯","à¤¦à¥à¤µ","à¤¦","à¤§à¥à¤°à¥","à¤§à¥","à¤§","à¤¨à¥à¤°à¥","à¤¨à¥à¤¨à¥","à¤¨à¥à¤¨","à¤¨à¥","à¤¨","à¤ªà¥à¤°à¥","à¤ªà¥à¤°","à¤ªà¥","à¤ª","à¥žà¥à¤°","à¤«à¥à¤°","à¥žà¥","à¥ž","à¤«à¥","à¤«","à¤¬à¥à¤°","à¤¬à¥","à¤¬","à¤­à¥à¤°à¥","à¤­à¥","à¤­","à¤®à¥à¤°à¥","à¤®à¥","à¤®","à¤¯à¥à¤°à¥","à¤¯à¥","à¤¯","à¤°à¥","à¤°à¥‚","à¤²à¥","à¤²","à¤³à¥","à¤³","à¤µà¥à¤°à¥","à¤µà¥","à¤µ","à¤¶à¥à¤µà¥","à¤¶à¥à¤µ","à¤¶à¥","à¤¶","à¤·à¥","à¤·","à¤¸à¥","à¤¸","à¤¹à¥ƒ","à¤¹à¥à¤°","à¤¹à¥à¤®","à¤¹à¥à¤¯","à¤¹à¥","à¤¹","à¥à¤°","à¤°","à¤","à¤‚","à¥‡à¤‚","à¥ˆà¤‚","à¥‡","à¥ˆ","à¥‹","à¥Œ","à¤¾","à¥€","à¥","à¥‚","à¥ƒ","à¥„","à¥…","à¥")
var array_two=new Array("à¥˜à¥","à¥™à¥","à¥šà¥","à¥›à¥","à¥žà¥","à¥˜","à¥™","à¥š","à¥›","à¥ž","à¥œ","à¥","$","%","&","*","Â¸","Â¸Ã‰","+Ã‰Ã¬","Ã‰Ã¬","à¤†Ã¥","à¤†Ã©","+Ã‰Ã¤","+Ã‰Ã¨","+Ã‰","+","<Ã‡","<",">Ã²","=","@","A","BÃ¤","B","GÃ²","HÃ²","I","IÃ‰","D","FÃ²","C","EÃ²","K","KÃ‰","L","J","JÃ‰","N","NÃ‰","O","OÃ‰","M","MÃ‰","Q","P","PÃ‰","R","T","S","SÃ‰","U","W","WÃ‰","X","Y","YÃ‰","V","VÃ‰","[","Z","ZÃ‰","\\","\\Ã‰","^","_","]","a","`","c","d","e","b","g","f","h","hÃ‰","j","jÃ‰","k","kÃ‰","i","iÃ‰","m","l","lÃ‰","o","p","q","r","s","t","u","n","w","v","vÃ‰","y","z","zÃ‰","x","xÃ‰","|","|Ã‰","{","{Ã‰","Â£ÃƒÃ²","Â£Ã²","~","Â¢Ã²","}","Â¡Ã²","Â¥","Â¤","Â¤Ã‰","Â§","Â¦","Â¦Ã‰","Â©","Â¨","Â¨Ã‰","Â«","Âª","ÂªÃ‰","Â»","Â°Ã²","Â±","Â±Ã‰","Â²","Â³","Âµ","Â´","Â´Ã‰","â€¢","â€¢Ã‰","Â¶","Â¶Ã‰","Â¹","Â¹Ã‰","Âº","ÂºÃ‰","Ã€","Ã","Â¾","Â¿","Â¼","Â½","Ã…","Â®","Ã„","Ã†","Ã¥","Ã©","Ã¤","Ã¨","Ã‰Ã¤","Ã‰Ã¨","Ã‰","Ã’","Ã™","Ãš","Ãž","ÃŸ","Ã¬","Ã‚")
var array_one_length=array_one.length;var modified_substring=document.getElementById("legacy_text").value;Replace_Symbols();processed_text=modified_substring;document.getElementById("dvttyogesh_text").value=processed_text;function Replace_Symbols()
{if(modified_substring!="")
{modified_substring=modified_substring.replace(/à¤•à¤¼/,"à¥˜");modified_substring=modified_substring.replace(/à¤–à¤¼â€Œ/g,"à¥™");modified_substring=modified_substring.replace(/à¤—à¤¼/g,"à¥š");modified_substring=modified_substring.replace(/à¤œà¤¼/g,"à¥›");modified_substring=modified_substring.replace(/à¤¡à¤¼/g,"à¥œ");modified_substring=modified_substring.replace(/à¤¢à¤¼/g,"à¥");modified_substring=modified_substring.replace(/à¤¨à¤¼/g,"à¤©");modified_substring=modified_substring.replace(/à¤«à¤¼/g,"à¥ž");modified_substring=modified_substring.replace(/à¤¯à¤¼/g,"à¥Ÿ");modified_substring=modified_substring.replace(/à¤°à¤¼/g,"à¤±");var position_of_f=modified_substring.indexOf("à¤¿");while(position_of_f!=-1)
{var character_left_to_f=modified_substring.charAt(position_of_f-1);modified_substring=modified_substring.replace(character_left_to_f+"à¤¿","ÃŠ"+character_left_to_f);position_of_f=position_of_f-1;while((modified_substring.charAt(position_of_f-1)=="à¥")&(position_of_f!=0))
{var string_to_be_replaced=modified_substring.charAt(position_of_f-2)+"à¥";modified_substring=modified_substring.replace(string_to_be_replaced+"ÃŠ","ÃŠ"+string_to_be_replaced);position_of_f=position_of_f-2;}
position_of_f=modified_substring.search(/à¤¿/,position_of_f+1);}
set_of_matras="à¤¾à¤¿à¥€à¥à¥‚à¥ƒà¥‡à¥ˆà¥‹à¥Œà¤‚:à¤à¥…"
modified_substring+='  ';var position_of_half_R=modified_substring.indexOf("à¤°à¥");while(position_of_half_R>0)
{var probable_position_of_Z=position_of_half_R+2;var character_right_to_probable_position_of_Z=modified_substring.charAt(probable_position_of_Z+1)
while(set_of_matras.indexOf(character_right_to_probable_position_of_Z)!=-1)
{probable_position_of_Z=probable_position_of_Z+1;character_right_to_probable_position_of_Z=modified_substring.charAt(probable_position_of_Z+1);}
string_to_be_replaced=modified_substring.substr(position_of_half_R+2,(probable_position_of_Z-position_of_half_R-1));modified_substring=modified_substring.replace("à¤°à¥"+string_to_be_replaced,string_to_be_replaced+"Ã‡");position_of_half_R=modified_substring.indexOf("à¤°à¥");}
modified_substring=modified_substring.substr(0,modified_substring.length-2);for(input_symbol_idx=0;input_symbol_idx<array_one_length;input_symbol_idx++)
{idx=0;while(idx!=-1)
{modified_substring=modified_substring.replace(array_one[input_symbol_idx],array_two[input_symbol_idx])
idx=modified_substring.indexOf(array_one[input_symbol_idx])}}}}}
